import { COMMAND_NAMES, PANEL_COMMAND_NAMES } from "./command";
import { ROULETTE_ACTION_NAMES } from "./roulette";

/** actions.command_name に保存する内部識別子。英小文字とスネークケースで統一する。 */
export const ACTION_TYPES = {
  TRANSFER: "transfer",
  SHOP_PURCHASE: "shop_purchase",
  DARK_SHOP_PURCHASE: "dark_shop_purchase",
  CREATOR_EMBLEM_PAYMENT: "creator_emblem_payment",
  SUPERCHAT: "superchat",
  MARKET_GACHA_DRAW: "market_gacha_draw",
  OMIKUJI_DRAW: "omikuji_draw",
  ROLE_BASED_GRANT: "role_based_grant",
  ADMIN_MINT: "admin_mint",
  ADMIN_BURN: "admin_burn",
  SALARY_PAYMENT: "salary_payment",
  SERVER_BOOST_REWARD: "server_boost_reward",
  VC_REWARD: "vc_reward",
  DISPLAY_NAME_CHANGE: "display_name_change",
  HOTEL_NORMAL: "hotel_normal",
  HOTEL_SECRET: "hotel_secret",
  HOTEL_SECRET_LONG: "hotel_secret_long",
  HOTEL_FREEDOM: "hotel_freedom",
  HOTEL_FREEDOM_LONG: "hotel_freedom_long",
  SOLITARY_CELL: "solitary_cell",
  DIARY_PRIVATE: "diary_private",
  DIARY_PUBLIC: "diary_public",
  DIARY_UPDATE: "diary_update",
  CASINO_GF: "casino_gf",
  CASINO_MAHJONG: "casino_mahjong",
  CASINO_OTHER: "casino_other",
  GAME_SHORT: "game_short",
  GAME_LONG: "game_long",
  GAME_SHORT_EXTEND: "game_short_extend",
  GAME_PASS: "game_pass",
  MINECRAFT_PASS: "minecraft_pass",
  HAZAMA_ACCESS: "hazama_access",
  ROULETTE_BET: "roulette_bet",
  ROULETTE_PAYOUT: "roulette_payout",
  ROULETTE_BONUS: "roulette_bonus",
} as const;

const ACTION_TYPE_BY_COMMAND_NAME: Record<string, string> = {
  [PANEL_COMMAND_NAMES.SEND]: ACTION_TYPES.TRANSFER,
  [PANEL_COMMAND_NAMES.SHOP_SEND]: ACTION_TYPES.SHOP_PURCHASE,
  [PANEL_COMMAND_NAMES.DARK_SHOP_SEND]: ACTION_TYPES.DARK_SHOP_PURCHASE,
  [PANEL_COMMAND_NAMES.CREATOR_EMBLEM_PAY]: ACTION_TYPES.CREATOR_EMBLEM_PAYMENT,
  [PANEL_COMMAND_NAMES.SUPERCHAT_SEND]: ACTION_TYPES.SUPERCHAT,
  [PANEL_COMMAND_NAMES.MARKET_GACHA_DRAW]: ACTION_TYPES.MARKET_GACHA_DRAW,
  [PANEL_COMMAND_NAMES.OMIKUJI_DRAW]: ACTION_TYPES.OMIKUJI_DRAW,
  [PANEL_COMMAND_NAMES.ADMIN_MINT]: ACTION_TYPES.ADMIN_MINT,
  [PANEL_COMMAND_NAMES.ADMIN_BURN]: ACTION_TYPES.ADMIN_BURN,
  [PANEL_COMMAND_NAMES.HOTEL_VC_NORMAL]: ACTION_TYPES.HOTEL_NORMAL,
  [PANEL_COMMAND_NAMES.HOTEL_VC_SECRET]: ACTION_TYPES.HOTEL_SECRET,
  [PANEL_COMMAND_NAMES.HOTEL_VC_SECRETLONG]: ACTION_TYPES.HOTEL_SECRET_LONG,
  [PANEL_COMMAND_NAMES.HOTEL_VC_FREEDOM]: ACTION_TYPES.HOTEL_FREEDOM,
  [PANEL_COMMAND_NAMES.HOTEL_VC_FREEDOMLONG]: ACTION_TYPES.HOTEL_FREEDOM_LONG,
  [PANEL_COMMAND_NAMES.SOLITARY_CELL_CREATE]: ACTION_TYPES.SOLITARY_CELL,
  [PANEL_COMMAND_NAMES.DIARY_PRIVATE]: ACTION_TYPES.DIARY_PRIVATE,
  [PANEL_COMMAND_NAMES.DIARY_PUBLIC]: ACTION_TYPES.DIARY_PUBLIC,
  [PANEL_COMMAND_NAMES.DIARY_UPDATE]: ACTION_TYPES.DIARY_UPDATE,
  [PANEL_COMMAND_NAMES.CASINO_GF]: ACTION_TYPES.CASINO_GF,
  [PANEL_COMMAND_NAMES.CASINO_MAJONG]: ACTION_TYPES.CASINO_MAHJONG,
  [PANEL_COMMAND_NAMES.CASINO_OTHER]: ACTION_TYPES.CASINO_OTHER,
  [PANEL_COMMAND_NAMES.GAME_SHORT]: ACTION_TYPES.GAME_SHORT,
  [PANEL_COMMAND_NAMES.GAME_LONG]: ACTION_TYPES.GAME_LONG,
  [PANEL_COMMAND_NAMES.GAME_SHORT_EXTEND]: ACTION_TYPES.GAME_SHORT_EXTEND,
  [PANEL_COMMAND_NAMES.GAME_PASS]: ACTION_TYPES.GAME_PASS,
  [PANEL_COMMAND_NAMES.MINECRAFT_PASS]: ACTION_TYPES.MINECRAFT_PASS,
  [PANEL_COMMAND_NAMES.HAZAMA_ACCESS]: ACTION_TYPES.HAZAMA_ACCESS,
  [COMMAND_NAMES.ROLE_BASED_SEND]: ACTION_TYPES.ROLE_BASED_GRANT,
  [COMMAND_NAMES.PAY_SALARY]: ACTION_TYPES.SALARY_PAYMENT,
  [COMMAND_NAMES.SERVER_BOOST]: ACTION_TYPES.SERVER_BOOST_REWARD,
  [COMMAND_NAMES.VC_REWARD]: ACTION_TYPES.VC_REWARD,
  [COMMAND_NAMES.CHANGE_NAME]: ACTION_TYPES.DISPLAY_NAME_CHANGE,
  [ROULETTE_ACTION_NAMES.BET]: ACTION_TYPES.ROULETTE_BET,
  [ROULETTE_ACTION_NAMES.PAYOUT]: ACTION_TYPES.ROULETTE_PAYOUT,
  [ROULETTE_ACTION_NAMES.BONUS]: ACTION_TYPES.ROULETTE_BONUS,
};

const actionTypeValues = new Set<string>(Object.values(ACTION_TYPES));

export function toActionType(commandName: string): string {
  if (actionTypeValues.has(commandName)) return commandName;
  const actionType = ACTION_TYPE_BY_COMMAND_NAME[commandName];
  if (!actionType) {
    throw new Error(`actions.command_name に未登録の操作です: ${commandName}`);
  }
  return actionType;
}
