// 外部の絵文字
export const EXTERNALE_MOJI_VIEWS = {
  WALLET: "💳",
  CURRENCY_COIN: "🪙",
  MOON: "🌙",
  MILKY_WAY: "🌌",
  UNIVESE: "🪐",
  SPACE: "🚀",
  HISTORY: "💹",
  GF: "⚔️",
  MAJONG: "🀄",
  OTHER: "🎲",
  PEOPLE: "🫂",
  NAME: "📝",
  SHORT: "✨",
  LONG: "💎",
  SHORT_EXTEND: "⏰",
  LONG_EXTEND: "⌚",
  GAME_PASS: "🎫",
  PREVIOUS: "◀️",
  NEXT: "▶️",
  RESTART: "🔄",
};
