import { ROLE_IDS } from "./id";

export const SERVER_BOOST_FIRST_REWARD = 30000;
export const SERVER_BOOST_AFTER_REWARD = 5000;
export const SERVER_BOOST_HIGH_REWARD_COUNT = 2;

// 月ごとの給与額。0 のロールには給与を支給しません。
export const SALARY_PAYMENTS: Record<string, number> = {
  // 運営
  [ROLE_IDS.SABANUSI]: 1000000,
  [ROLE_IDS.KANRISYA]: 500000,

  // 各カテゴリのリーダー
  [ROLE_IDS.MENSETU_LEADER]: 150000,
  [ROLE_IDS.GIJUTU_LEADER]: 200000,
  [ROLE_IDS.GINKOU_LEADER]: 200000,
  [ROLE_IDS.EVALUATION_LEADER]: 250000,
  [ROLE_IDS.SHOP_LEADER]: 150000,
  [ROLE_IDS.GAME_LEADER]: 130000,
  [ROLE_IDS.SHOKUNIN_LEADER]: 150000,
  [ROLE_IDS.EVENT_LEADER]: 170000,
  [ROLE_IDS.MONSTER_LEADER]: 150000,

  // 評価員
  [ROLE_IDS.EVALUATION_1KYUU]: 200000,
  [ROLE_IDS.EVALUATION_2KYUU]: 150000,
  [ROLE_IDS.EVALUATION_3KYUU]: 100000,
  [ROLE_IDS.EVALUATION_BUIGINNER]: 0,

  // 各カテゴリの従業員
  [ROLE_IDS.MENSTUKAN]: 0,
  [ROLE_IDS.MENSTU_BUIGINNER]: 0,
  [ROLE_IDS.GINKOU_STAFF]: 50000,
  [ROLE_IDS.SHOP_STAFF]: 30000,
  [ROLE_IDS.GAME_STAFF]: 30000,
  [ROLE_IDS.SHOKUNIN_STAFF]: 0,
  [ROLE_IDS.EVENT_STAFF]: 0,
  [ROLE_IDS.MONSTER_STAFF]: 50000,

  // メンバー
  [ROLE_IDS.CORE_MEMBER_ROLES.HONMEN]: 60000,
  [ROLE_IDS.CORE_MEMBER_ROLES.JUNHONMEN]: 40000,
};
export const SALARY_ROLE_IDS: Record<string, string> = {
  SABANUSI: ROLE_IDS.SABANUSI,
  KANRISYA: ROLE_IDS.KANRISYA,

  MENSETU_LEADER: ROLE_IDS.MENSETU_LEADER,
  GIJUTU_LEADER: ROLE_IDS.GIJUTU_LEADER,
  GINKOU_LEADER: ROLE_IDS.GINKOU_LEADER,
  EVALUATION_LEADER: ROLE_IDS.EVALUATION_LEADER,
  SHOP_LEADER: ROLE_IDS.SHOP_LEADER,
  GAME_LEADER: ROLE_IDS.GAME_LEADER,
  SHOKUNIN_LEADER: ROLE_IDS.SHOKUNIN_LEADER,
  EVENT_LEADER: ROLE_IDS.EVENT_LEADER,
  MONSTER_LEADER: ROLE_IDS.MONSTER_LEADER,

  EVALUATION_1KYUU: ROLE_IDS.EVALUATION_1KYUU,
  EVALUATION_2KYUU: ROLE_IDS.EVALUATION_2KYUU,
  EVALUATION_3KYUU: ROLE_IDS.EVALUATION_3KYUU,
  EVALUATION_BUIGINNER: ROLE_IDS.EVALUATION_BUIGINNER,

  MENSTUKAN: ROLE_IDS.MENSTUKAN,
  MENSTU_BUIGINNER: ROLE_IDS.MENSTU_BUIGINNER,
  GINKOU_STAFF: ROLE_IDS.GINKOU_STAFF,
  SHOP_STAFF: ROLE_IDS.SHOP_STAFF,
  GAME_STAFF: ROLE_IDS.GAME_STAFF,
  SHOKUNIN_STAFF: ROLE_IDS.SHOKUNIN_STAFF,
  EVENT_STAFF: ROLE_IDS.EVENT_STAFF,
  MONSTER_STAFF: ROLE_IDS.MONSTER_STAFF,

  HONMEN: ROLE_IDS.CORE_MEMBER_ROLES.HONMEN,
  JUNHONMEN: ROLE_IDS.CORE_MEMBER_ROLES.JUNHONMEN,
};

export const TEST_SALARY_PAYMENTS: Record<string, number> = {};
export const TEST_SALARY_ROLE_IDS: Record<string, string> = {};
