import { ROLE_IDS, TEST_ROLE_IDS } from "../constant/id";

export const SERVER_BOOST_FIRST_REWARD = 30000;
export const SERVER_BOOST_AFTER_REWARD = 5000;

export const SALARY_PAYMENTS = {
  [ROLE_IDS.SOUZOUSYU]: 1000000,
  [ROLE_IDS.SIKKOKAN]: 500000,
  [ROLE_IDS.GIJUTU_LEADER]: 180000,
  [ROLE_IDS.MENSETU_LEADER]: 150000,
  [ROLE_IDS.GINKOU_LEADER]: 200000,
  [ROLE_IDS.SHOP_LEADER]: 170000,
  [ROLE_IDS.GAME_LEADER]: 150000,
  [ROLE_IDS.CASINO_LEADER]: 150000,
  [ROLE_IDS.SHOKUNIN_LEADER]: 160000,
  [ROLE_IDS.HOTEL_LEADER]:140000,
  [ROLE_IDS.MONSTER_LEADER]: 150000,
  [ROLE_IDS.EVALUATION_LEADER]: 250000,
  [ROLE_IDS.EVALUATION_1KYUU]: 200000,
  [ROLE_IDS.EVALUATION_2KYUU]: 150000,
  [ROLE_IDS.EVALUATION_3KYUU]: 100000,
  [ROLE_IDS.EVALUATION_SUB_LEADER]: 100000,
  [ROLE_IDS.GINKO_SUB_LEADER]: 80000,
  [ROLE_IDS.GINKOU_STAFF]: 30000,
  [ROLE_IDS.SHOP_STAFF]: 30000,
  [ROLE_IDS.GAME_STAFF]: 30000,
  [ROLE_IDS.HOTEL_STAFF]: 30000,
  [ROLE_IDS.MONSTER_STAFF]: 50000,
  [ROLE_IDS.CORE_MEMBER_ROLES.KOKUIN]: 60000,
  [ROLE_IDS.CORE_MEMBER_ROLES.KEIYAKU]: 40000,
  [ROLE_IDS.CORE_MEMBER_ROLES.MIKEIYAKU]: 10000,
  [ROLE_IDS.MONSTER_1KYUU]: 30000,
  [ROLE_IDS.MONSTER_2KYUU]: 20000,
  [ROLE_IDS.MONSTER_3KYUU]: 10000,
};

export const SALARY_ROLE_IDS = {
  SOUZOUSYU: ROLE_IDS.SOUZOUSYU, // 創造主ロールID
  SIKKOKAN: ROLE_IDS.SIKKOKAN, // 執行人ロールID
  GIJUTU_LEADER: ROLE_IDS.GIJUTU_LEADER, // 技術統括ロールID
  MENSETU_LEADER: ROLE_IDS.MENSETU_LEADER, // 面接統括ロールID
  GINKOU_LEADER: ROLE_IDS.GINKOU_LEADER, // 銀行統括ロールID
  SHOP_LEADER: ROLE_IDS.SHOP_LEADER, // ショップ統括ロールID
  GAME_LEADER: ROLE_IDS.GAME_LEADER, // ゲーム統括ロールID
  CASINO_LEADER: ROLE_IDS.CASINO_LEADER, // カジノ統括ロールID
  SHOKUNIN_LEADER: ROLE_IDS.SHOKUNIN_LEADER, // 職人統括ロールID
  HOTEL_LEADER: ROLE_IDS.HOTEL_LEADER, // ホテル統括ロールID
  MONSTER_LEADER: ROLE_IDS.MONSTER_LEADER, // 魔物統括ロールID
  EVALUATION_LEADER: ROLE_IDS.EVALUATION_LEADER, // 評価統括ロールID
  EVALUATION_1KYUU: ROLE_IDS.EVALUATION_1KYUU, // 評価1級ロールID
  EVALUATION_2KYUU: ROLE_IDS.EVALUATION_2KYUU, // 評価2級ロールID
  EVALUATION_3KYUU: ROLE_IDS.EVALUATION_3KYUU, // 評価3級ロールID
  EVALUATION_SUB_LEADER: ROLE_IDS.EVALUATION_SUB_LEADER, // 評価副統括ロールID
  GINKO_SUB_LEADER: ROLE_IDS.GINKO_SUB_LEADER, // 銀行副統括ロールID
  GINKOU_STAFF: ROLE_IDS.GINKOU_STAFF, // 銀行従業員ロールID
  SHOP_STAFF: ROLE_IDS.SHOP_STAFF, // ショップ従業員ロールID
  GAME_STAFF: ROLE_IDS.GAME_STAFF, // ゲーム従業員ロールID
  HOTEL_STAFF: ROLE_IDS.HOTEL_STAFF, // ホテル従業員ロールID
  MONSTER_STAFF: ROLE_IDS.MONSTER_STAFF, // 魔物従業員ロールID
  KOKUIN: ROLE_IDS.CORE_MEMBER_ROLES.KOKUIN, // 刻印ロールID
  KEIYAKU: ROLE_IDS.CORE_MEMBER_ROLES.KEIYAKU, // 契約ロールID
  MIKEIYAKU: ROLE_IDS.CORE_MEMBER_ROLES.MIKEIYAKU, // 未契約ロールID
  MONSTER_1KYUU: ROLE_IDS.MONSTER_1KYUU, // 魔物1級ロールID
  MONSTER_2KYUU: ROLE_IDS.MONSTER_2KYUU, // 魔物2級ロールID
  MONSTER_3KYUU: ROLE_IDS.MONSTER_3KYUU, // 魔物3級ロールID
};

export const TEST_SALARY_PAYMENTS = {
  [TEST_ROLE_IDS.SALARY_ROLE_IDS.TEST_1]: 111,
  [TEST_ROLE_IDS.SALARY_ROLE_IDS.TEST_2]: 222,
};

export const TEST_SALARY_ROLE_IDS = {
  TEST_1: TEST_ROLE_IDS.SALARY_ROLE_IDS.TEST_1,
  TEST_2: TEST_ROLE_IDS.SALARY_ROLE_IDS.TEST_2,
};
