import { ROLE_IDS } from "./id";

export const MANAGEMENT_ROLE_IDS = [ROLE_IDS.KANRISYA, ROLE_IDS.SABANUSI, ROLE_IDS.GIJUTU_LEADER];
export const MANAGEMENT_HANDLER_TIMEOUT_MS = 5 * 60 * 1000;
export const VC_CLEAN_DURATION_MS = 2 * 60 * 1000;
