export const DEFAULT_ACK_TIMEOUT_MS = 30_000;

export const DEFAULT_HANDLER_TIMEOUT_MS = 45_000;

export const DEFAULT_GATEWAY_DISCONNECT_TIMEOUT_MS = 300_000;

export const DEFAULT_HEALTH_CHECK_INTERVAL_MS = 15_000;

export const DEFAULT_MAX_CONSECUTIVE_ACK_FAILURES = 3;
