import { ROLE_IDS } from "../shared/id";

export const SERVER_BOOST_FIRST_REWARD = 30000;
export const SERVER_BOOST_AFTER_REWARD = 5000;
export const SERVER_BOOST_HIGH_REWARD_COUNT = 2;

// 月ごとの給与額。ここに記載した21ロールのみを支給対象とします。
export const SALARY_PAYMENTS: Record<string, number> = {
  // 運営
  [ROLE_IDS.SABANUSI]: 2000000,
  [ROLE_IDS.KANRISYA]: 1500000,

  // 各カテゴリのリーダー
  [ROLE_IDS.EVENT_LEADER]: 180000,
  [ROLE_IDS.GINKOU_LEADER]: 300000,
  [ROLE_IDS.PILGRIM_LEADER]: 200000,
  [ROLE_IDS.SHOP_LEADER]: 200000,
  [ROLE_IDS.DARK_SHOP_LEADER]: 190000,
  [ROLE_IDS.STREAMER_MANAGER]: 170000,
  [ROLE_IDS.GAME_LEADER]: 200000,
  [ROLE_IDS.SHOKUNIN_LEADER]: 180000,
  [ROLE_IDS.COURT_LEADER]: 250000,
  [ROLE_IDS.HAZAMA_LEADER]: 170000,
  [ROLE_IDS.MONSTER_LEADER]: 180000,
  [ROLE_IDS.GIJUTU_LEADER]: 300000,

  // 各カテゴリの従業員
  [ROLE_IDS.GINKOU_STAFF]: 80000,
  [ROLE_IDS.SHOP_STAFF]: 50000,
  [ROLE_IDS.PRODUCER]: 30000,
  [ROLE_IDS.MONSTER_STAFF]: 30000,

  // 活動者
  [ROLE_IDS.SINGER_CROWN]: 40000,

  // メンバー
  [ROLE_IDS.CORE_MEMBER_ROLES.HONMEN]: 60000,
  [ROLE_IDS.CORE_MEMBER_ROLES.JUNHONMEN]: 40000,
};
export const SALARY_ROLE_IDS: Record<string, string> = {
  SABANUSI: ROLE_IDS.SABANUSI,
  KANRISYA: ROLE_IDS.KANRISYA,

  EVENT_LEADER: ROLE_IDS.EVENT_LEADER,
  GINKOU_LEADER: ROLE_IDS.GINKOU_LEADER,
  PILGRIM_LEADER: ROLE_IDS.PILGRIM_LEADER,
  SHOP_LEADER: ROLE_IDS.SHOP_LEADER,
  DARK_SHOP_LEADER: ROLE_IDS.DARK_SHOP_LEADER,
  STREAMER_MANAGER: ROLE_IDS.STREAMER_MANAGER,
  GAME_LEADER: ROLE_IDS.GAME_LEADER,
  SHOKUNIN_LEADER: ROLE_IDS.SHOKUNIN_LEADER,
  COURT_LEADER: ROLE_IDS.COURT_LEADER,
  HAZAMA_LEADER: ROLE_IDS.HAZAMA_LEADER,
  MONSTER_LEADER: ROLE_IDS.MONSTER_LEADER,
  GIJUTU_LEADER: ROLE_IDS.GIJUTU_LEADER,

  GINKOU_STAFF: ROLE_IDS.GINKOU_STAFF,
  SHOP_STAFF: ROLE_IDS.SHOP_STAFF,
  PRODUCER: ROLE_IDS.PRODUCER,
  MONSTER_STAFF: ROLE_IDS.MONSTER_STAFF,

  SINGER_CROWN: ROLE_IDS.SINGER_CROWN,

  HONMEN: ROLE_IDS.CORE_MEMBER_ROLES.HONMEN,
  JUNHONMEN: ROLE_IDS.CORE_MEMBER_ROLES.JUNHONMEN,
};

export const TEST_SALARY_PAYMENTS: Record<string, number> = {};
export const TEST_SALARY_ROLE_IDS: Record<string, string> = {};

// 臨時に給与振込を停止する日付（JST）。翌月以降の定期振込には影響しない。
export const SKIPPED_MONTHLY_SALARY_PAYMENT_DATES = ["2026-09-01"] as const;
